# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1406, 895)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(1120, 30, 281, 511))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 279, 509))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.searchTabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents_2)
        self.searchTabWidget.setGeometry(QtCore.QRect(0, 0, 281, 511))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.searchTabWidget.setFont(font)
        self.searchTabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.searchTabWidget.setObjectName("searchTabWidget")
        self.index_tab = QtWidgets.QWidget()
        self.index_tab.setObjectName("index_tab")
        self.createIndex_btn = QtWidgets.QPushButton(self.index_tab)
        self.createIndex_btn.setGeometry(QtCore.QRect(20, 410, 111, 41))
        self.createIndex_btn.setObjectName("createIndex_btn")
        self.indexSelectBox1 = QtWidgets.QComboBox(self.index_tab)
        self.indexSelectBox1.setGeometry(QtCore.QRect(20, 50, 241, 31))
        self.indexSelectBox1.setEditable(False)
        self.indexSelectBox1.setObjectName("indexSelectBox1")
        self.indexSelectBox1.addItem("")
        self.indexSelectBox1.addItem("")
        self.indexLabel1 = QtWidgets.QLabel(self.index_tab)
        self.indexLabel1.setGeometry(QtCore.QRect(20, 20, 201, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.indexLabel1.setFont(font)
        self.indexLabel1.setObjectName("indexLabel1")
        self.indexSelectBox2 = QtWidgets.QComboBox(self.index_tab)
        self.indexSelectBox2.setGeometry(QtCore.QRect(20, 130, 241, 31))
        self.indexSelectBox2.setEditable(False)
        self.indexSelectBox2.setObjectName("indexSelectBox2")
        self.indexLabel2 = QtWidgets.QLabel(self.index_tab)
        self.indexLabel2.setGeometry(QtCore.QRect(20, 100, 201, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.indexLabel2.setFont(font)
        self.indexLabel2.setObjectName("indexLabel2")
        self.showIndexes_btn = QtWidgets.QPushButton(self.index_tab)
        self.showIndexes_btn.setGeometry(QtCore.QRect(150, 410, 111, 41))
        self.showIndexes_btn.setObjectName("showIndexes_btn")
        self.indexEdit = QtWidgets.QTextEdit(self.index_tab)
        self.indexEdit.setGeometry(QtCore.QRect(20, 190, 241, 131))
        self.indexEdit.setObjectName("indexEdit")
        self.indexNameLabel = QtWidgets.QLabel(self.index_tab)
        self.indexNameLabel.setGeometry(QtCore.QRect(30, 350, 51, 31))
        self.indexNameLabel.setObjectName("indexNameLabel")
        self.indexNameEdit = QtWidgets.QLineEdit(self.index_tab)
        self.indexNameEdit.setGeometry(QtCore.QRect(92, 350, 161, 31))
        self.indexNameEdit.setObjectName("indexNameEdit")
        self.searchTabWidget.addTab(self.index_tab, "")
        self.special_search_tab = QtWidgets.QWidget()
        self.special_search_tab.setObjectName("special_search_tab")
        self.specialSelectBox = QtWidgets.QComboBox(self.special_search_tab)
        self.specialSelectBox.setGeometry(QtCore.QRect(20, 10, 241, 31))
        self.specialSelectBox.setEditable(False)
        self.specialSelectBox.setObjectName("specialSelectBox")
        self.specialSelectBox.addItem("")
        self.specialSelectBox.addItem("")
        self.specialSelectBox.addItem("")
        self.selectBox_group1 = QtWidgets.QComboBox(self.special_search_tab)
        self.selectBox_group1.setGeometry(QtCore.QRect(20, 90, 241, 31))
        self.selectBox_group1.setEditable(False)
        self.selectBox_group1.setObjectName("selectBox_group1")
        self.selectBox_group1.addItem("")
        self.selectBox_group1.addItem("")
        self.selectLabel_group1 = QtWidgets.QLabel(self.special_search_tab)
        self.selectLabel_group1.setGeometry(QtCore.QRect(20, 60, 201, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.selectLabel_group1.setFont(font)
        self.selectLabel_group1.setObjectName("selectLabel_group1")
        self.specialCreateView_btn = QtWidgets.QPushButton(self.special_search_tab)
        self.specialCreateView_btn.setGeometry(QtCore.QRect(150, 410, 111, 41))
        self.specialCreateView_btn.setObjectName("specialCreateView_btn")
        self.specialSearch_btn = QtWidgets.QPushButton(self.special_search_tab)
        self.specialSearch_btn.setGeometry(QtCore.QRect(20, 410, 111, 41))
        self.specialSearch_btn.setObjectName("specialSearch_btn")
        self.selectBox_group2 = QtWidgets.QComboBox(self.special_search_tab)
        self.selectBox_group2.setGeometry(QtCore.QRect(20, 170, 241, 31))
        self.selectBox_group2.setEditable(False)
        self.selectBox_group2.setObjectName("selectBox_group2")
        self.selectLabel_group2 = QtWidgets.QLabel(self.special_search_tab)
        self.selectLabel_group2.setGeometry(QtCore.QRect(20, 140, 201, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.selectLabel_group2.setFont(font)
        self.selectLabel_group2.setObjectName("selectLabel_group2")
        self.searchTabWidget.addTab(self.special_search_tab, "")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setGeometry(QtCore.QRect(0, 0, 281, 811))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 279, 809))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.pokebase_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.pokebase_label.setGeometry(QtCore.QRect(10, 0, 101, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pokebase_label.setFont(font)
        self.pokebase_label.setObjectName("pokebase_label")
        self.table_list = QtWidgets.QListWidget(self.scrollAreaWidgetContents_3)
        self.table_list.setGeometry(QtCore.QRect(0, 30, 281, 781))
        self.table_list.setResizeMode(QtWidgets.QListView.Adjust)
        self.table_list.setObjectName("table_list")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(300, 0, 801, 811))
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setGeometry(QtCore.QRect(0, 30, 791, 741))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 789, 739))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.table_info = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.table_info.setGeometry(QtCore.QRect(0, 0, 791, 741))
        self.table_info.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_info.setObjectName("table_info")
        self.table_info.setColumnCount(0)
        self.table_info.setRowCount(0)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.add_btn = QtWidgets.QPushButton(self.tab)
        self.add_btn.setGeometry(QtCore.QRect(0, 0, 61, 31))
        self.add_btn.setObjectName("add_btn")
        self.delete_btn = QtWidgets.QPushButton(self.tab)
        self.delete_btn.setGeometry(QtCore.QRect(60, 0, 61, 31))
        self.delete_btn.setObjectName("delete_btn")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.tab)
        self.buttonBox.setEnabled(False)
        self.buttonBox.setGeometry(QtCore.QRect(590, 0, 193, 28))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget.addTab(self.tab, "")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_4.setGeometry(QtCore.QRect(1120, 550, 281, 251))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 279, 249))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.sql_text = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_4)
        self.sql_text.setGeometry(QtCore.QRect(0, 30, 281, 221))
        self.sql_text.setObjectName("sql_text")
        self.sql_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.sql_label.setGeometry(QtCore.QRect(10, 0, 81, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.sql_label.setFont(font)
        self.sql_label.setObjectName("sql_label")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.error_label = QtWidgets.QLabel(self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(10, 820, 1381, 20))
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1406, 26))
        self.menubar.setObjectName("menubar")
        self.database_menu = QtWidgets.QMenu(self.menubar)
        self.database_menu.setObjectName("database_menu")
        self.table_menu = QtWidgets.QMenu(self.menubar)
        self.table_menu.setObjectName("table_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.connect_action = QtWidgets.QAction(MainWindow)
        self.connect_action.setCheckable(True)
        self.connect_action.setObjectName("connect_action")
        self.disconnect_action = QtWidgets.QAction(MainWindow)
        self.disconnect_action.setCheckable(True)
        self.disconnect_action.setObjectName("disconnect_action")
        self.add_action = QtWidgets.QAction(MainWindow)
        self.add_action.setCheckable(True)
        self.add_action.setObjectName("add_action")
        self.delete_action = QtWidgets.QAction(MainWindow)
        self.delete_action.setCheckable(True)
        self.delete_action.setObjectName("delete_action")
        self.database_menu.addAction(self.connect_action)
        self.database_menu.addAction(self.disconnect_action)
        self.table_menu.addAction(self.add_action)
        self.table_menu.addAction(self.delete_action)
        self.menubar.addAction(self.database_menu.menuAction())
        self.menubar.addAction(self.table_menu.menuAction())

        self.retranslateUi(MainWindow)
        self.searchTabWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.createIndex_btn.setText(_translate("MainWindow", "创建索引"))
        self.indexSelectBox1.setItemText(0, _translate("MainWindow", "pokemon_stats"))
        self.indexSelectBox1.setItemText(1, _translate("MainWindow", "move"))
        self.indexLabel1.setText(_translate("MainWindow", "请选择表"))
        self.indexLabel2.setText(_translate("MainWindow", "请选择属性"))
        self.showIndexes_btn.setText(_translate("MainWindow", "索引列表"))
        self.indexNameLabel.setText(_translate("MainWindow", "索引名"))
        self.searchTabWidget.setTabText(self.searchTabWidget.indexOf(self.index_tab), _translate("MainWindow", "索引"))
        self.specialSelectBox.setItemText(0, _translate("MainWindow", "连接查询"))
        self.specialSelectBox.setItemText(1, _translate("MainWindow", "嵌套查询"))
        self.specialSelectBox.setItemText(2, _translate("MainWindow", "分组查询"))
        self.selectBox_group1.setItemText(0, _translate("MainWindow", "pokemon_stats"))
        self.selectBox_group1.setItemText(1, _translate("MainWindow", "move"))
        self.selectLabel_group1.setText(_translate("MainWindow", "请选择查询的表"))
        self.specialCreateView_btn.setText(_translate("MainWindow", "创建视图"))
        self.specialSearch_btn.setText(_translate("MainWindow", "查 询"))
        self.selectLabel_group2.setText(_translate("MainWindow", "请选择用于分组的属性"))
        self.searchTabWidget.setTabText(self.searchTabWidget.indexOf(self.special_search_tab), _translate("MainWindow", "特殊查询"))
        self.pokebase_label.setText(_translate("MainWindow", "Pokebase"))
        self.add_btn.setText(_translate("MainWindow", "添加"))
        self.delete_btn.setText(_translate("MainWindow", "删除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "表"))
        self.sql_label.setText(_translate("MainWindow", "SQL命令"))
        self.database_menu.setTitle(_translate("MainWindow", "数据库"))
        self.table_menu.setTitle(_translate("MainWindow", "   表   "))
        self.connect_action.setText(_translate("MainWindow", "连接"))
        self.disconnect_action.setText(_translate("MainWindow", "断开"))
        self.add_action.setText(_translate("MainWindow", "添加"))
        self.delete_action.setText(_translate("MainWindow", "删除"))


